### ISSUE TITLE
Clever not found

### ISSUE THREAD

**Issue by Fan-loewe** [sfalexrog/jetson_camera#2]
Hello,

when I roslaunch the node, it shows the following error:
![image](https://user-images.githubusercontent.com/44665480/95081338-b1976d00-0719-11eb-9c01-ce67d59e81fd.png)

However, if I directly use gst-launch-1.0 according to https://www.jetsonhacks.com/2019/04/02/jetson-nano-raspberry-pi-camera/, it could start the camera correctly.

I am wondering whether I need a clever package, but I could not find it on the Internet.

Bests,
Fan

**Comment by Blackmamba-xuan** [comment]
> Hello,
> 
> when I roslaunch the node, it shows the following error:
> ![image](https://user-images.githubusercontent.com/44665480/95081338-b1976d00-0719-11eb-9c01-ce67d59e81fd.png)
> 
> However, if I directly use gst-launch-1.0 according to https://www.jetsonhacks.com/2019/04/02/jetson-nano-raspberry-pi-camera/, it could start the camera correctly.
> 
> I am wondering whether I need a clever package, but I could not find it on the Internet.
> 
> Bests,
> Fan

hi Fan, I got the same issue. Have you solved this problem?

**Comment by Fan-loewe** [comment]
@Blackmamba-xuan 
Hello I just commented the clever package in the launch file, you can use rqt_image_view to visualize that. 
Best, Fan
